### PR TITLE
Finish chapter "Lists, tables and trees"

### LINKED ISSUE #78: Finish chapter "Lists, tables and trees"
- [x] Check all code examples and images

### PR DESCRIPTION
**Pull request by koendehondt**
* Replaced all images except Moose image
* Tried all examples
* Improved text

### CODE REVIEW

**Comment by Ducasse** [comment]
I will have a look.

**Comment by Ducasse** [comment]
Are you sure about this asStringOrText (it looks not really nice to my eyes)?

**Comment by koendehondt** [comment]
> Are you sure about this asStringOrText (it looks not really nice to my eyes)?

Yes, I am sure. I checked all the code, so also this part. I was surprised too 😄.

See `SpListPresenter>>#initialize`:
```smalltalk
initialize

	super initialize.
	self initializeTSearchable.
	autoDeselect := true.
	allowToSelect := true.
	display := [ :object | object asStringOrText ]
```

**Comment by koendehondt** [comment]
@Ducasse I added all examples of this chapter to the code repo. See `ListTableAndTreeExamples`.
Doing so, I found a few issues in the text. I fixed them. See the latest commits.

**Comment by Ducasse** [comment]
In fact I would introduce a method that call Smalltalk globals allClasses because we should remove this Smalltalk variable in the future.

**Pull request merged**
