### PR TITLE
Finish chapter "Most of Spec in one example"

### PR DESCRIPTION
**Pull request by koendehondt**
This is the PR for #73.

It was quite some work to finish this long chapter. 😅

* The code has been changed accordingly. See https://github.com/SquareBracketAssociates/CodeOfSpec20Book/pull/4.
* A missing section to introduce the modal dialog has been added.
* All images have been replaced. They look much better now. They include correct film data.
* Many improvements to the text.
* See the checklist in #73 for more stuff that has been done.

### CODE REVIEW

**Comment by koendehondt** [comment]
@Ducasse If you do not have any comments or suggestions, I consider the chapter "Most of Spec in one example" to be finished. One more done! 😎

**Comment by Ducasse** [comment]
I will have a look and indeed it is long and it cost me time also in the past.

**Comment by Ducasse** [comment]
I read the complete chapter in speed mode and it looks good to me.

**Comment by koendehondt** [comment]
@Ducasse I overlooked that a test did not pass anymore after changing `#setModel:` to cope with a `nil` argument. I adapted the test and changed it in the book and in the code repo. I pushed the changes to the two master branches.

**Comment by Ducasse** [comment]
Cool!
I'm massively cleaning my house after the facade renewal (dust everywhere).

**Pull request merged**
