### PR TITLE
kdh review chapter 1

### PR DESCRIPTION
**Pull request by koendehondt**
@Ducasse This is a first PR with some suggestions for improvement. It is small on purpose. I like to try things out because I have never used Git for a book before.

I edited the files with VS Code, with the [PDF Viewer](https://marketplace.visualstudio.com/items?itemName=mathematic.vscode-pdf) extension, so that I can see the source and the PDF (after building with `pillar build pdf index.md`) side-by-side.

I noticed that the source included `^M^M` instead of newline characters. Therefore Git considers the whole chapter to be 1 line of text. The result is that the diff is large, instead of showing my small suggestions. That is annoying because you cannot see what I have changed.

Why does the source include `^M^M`? Shall I first open and save all chapters, so that we do not suffer from the same problem in other chapters?

### CODE REVIEW

**Comment by koendehondt** [comment]
```
file -I Chapters/Intro/Intro.md
Chapters/Intro/Intro.md: text/plain; charset=utf-8

file -I Chapters/CaseStudyOne/CaseStudyOne.md
Chapters/CaseStudyOne/CaseStudyOne.md: text/plain; charset=us-ascii
```

So the file encoding of `Intro.md` is different from the other files.
Note that the `file` command _attempts_ to classify a file. It reports `utf-8` because there are special characters in it (e.g. `^M`. I suggest to remove them, but I do not know how yet.

**Comment by koendehondt** [comment]
This is the problem with `Intro.md`:
1. It includes Windows-style line endings
2. It includes a curly quote in `Pharo’s objective`
3. It has names with accents

2 and 3 are the reason the file requires utf-8.
1 is a problem to see a decent diff in Git. I will replace all line endings with the line ending style of MacOS/Linux/... I will replace the curly quote by a regular quote (like elsewhere in the text).

Replacing the contents of the file did not solve the line ending problem, so I deleted the file and created another one with the same name

**Comment by Ducasse** [comment]
BTW I got problem with file encodings. So may be we should systematically convert the file ending 
in a first PR then we work on this version else this is super difficult to follow the changes.

**Comment by koendehondt** [comment]
I agree. So I propose:
* We disregard the PRs I made.
* I create a PR with corrected line endings for all files (I will check them all to be sure).
* I redo the PRs I already submitted.
* 
wdyt?

**Comment by Ducasse** [comment]
In fact I do not where the MM are coming from. May be when I converted file from Pillar to Microdown. 
Sometimes with textMate I succeeded to convert them all. I also tried with tr unix command line but I do not remember :(
I agree with your point on line ending and curly. No idea where it comes from. For the accents I like them :) 
and normally pillar manages them well.

**Pull request merged**
