### PR TITLE
Some changes to chapter "Styling Applications"

### PR DESCRIPTION
**Pull request by koendehondt**
This is a PR that solves some of the issues mentioned in #82. Most issues are still open.

### CODE REVIEW

**Comment by Ducasse** [comment]
Seems good to me. 
Let me know this is ok for review. 
Friday I will print the full book.

**Comment by koendehondt** [comment]
> Seems good to me. Let me know this is ok for review. Friday I will print the full book.

The chapter is not ready. There are still issues with the text. That is why the PR is "Draft".

**Comment by Ducasse** [comment]
Let me know when I can merge. 
I'm reprinting the complete book now.

**Comment by koendehondt** [comment]
@Ducasse 

> Let me know when I can merge. I'm reprinting the complete book now.

This PR includes changes to most images (in Pharo Light theme instead of Pharo Dark), but the chapter is far from finished because not all issues in #82 have been addressed yet.

**Pull request merged**
