### PR TITLE
draft proposal for Athens/Spec documentation

### PR DESCRIPTION
**Pull request by rvillemeur**
Hi.

This is still a work in progress. I saw that a chapter should talk about Athens/Spec. I summarized some note I took on my own to understand it. This is still a work in progress, but all example have been tested.

However, I'm not sure about the style and wording required to integrate it into the book. Furthermore, I don't  have any Pillar environment available to ensure that the formatting is correct. 

Any comment/advise would be welcome so I help further on documentation.

### CODE REVIEW

**Comment by Ducasse** [comment]
I feel super super bad. I never saw this chapter!

**Comment by Ducasse** [comment]
I think that I would like to add the part on Athens API to the doc folder in P11. 
I will read it and see but it could be a good addition to Pharo documentation

**Comment by rvillemeur** [comment]
This chapter was part of various notes I have taken on Pharo Graphical Stack - I wanted to understand computer graphics from the ground up, and Pharo, with all its history, has everything included.

Notes includes (in more or less draft format)
- The base of all: Forms - 1 bit, 2 bits, 4 bits, 8 bits, 16 bits and 32 bits.
- Explanation on color and RGB color definition
- Playing with forms - rotation, scaling, transition, etc...
- Creating Forms: Bitmap canvas
- Creating Forms: Vector Canvas and Athens =>  this is the chapter included here.
- Saving Forms - compressed image format: JPEG, PNG and GIF.
- Event management, and relationship with OSWindow
- Putting all together: Morphic
- Morphic Coordinates
- Morphic Events
- Morphic widget composition and layout.
- Morphic Animation
- Higher order graphics for "application de gestion": Spec.
- Spec Widget
- Spec Layout
- Spec style
- The future: Bloc, Brick - with example done in GToolkit, but can be reworked for Pharo
- bloc bounds
- bloc events
- bloc layout

Just wondering if this could be of interest, and where should I push them. I understand Morphic may not be relevant, but I can expand my notes on bloc to reflect the current state

**Comment by Ducasse** [comment]
Of course this is of interest. We could even have a separate booklet on that.
Today I did a pass on the Athens Spec integration chapter. 
If you send me an email I can send you the pdf. 
And now I'm looking at the athens part to see if I can turn it into a separate doc for Pharo 11.

**Comment by Ducasse** [comment]
I just created a booklet-graphics repo for a book. Feel free to push chapters there. 
I will review anything you push.

**Comment by rvillemeur** [comment]
sure, give me a few days to put back to md my files

**Comment by Ducasse** [comment]
I have an automatic converter from Pillar to md :)
so if you have some pillar just push them and I will convert them
`pillar convertChapter path ` :)

**Comment by rvillemeur** [comment]
Screenshot from 2023-01-06 15-35-12
My latest notes version are on gtoolkit. So i first need to go back to md files. I will do it asap. Glad to know they could be usefull

**Pull request merged**
